### ISSUE TITLE
numpy optional for AxisArray

### ISSUE THREAD

**Issue by cboulay** [ezmsg-org/ezmsg#160]
I guess this rarely comes up because almost everything using ezmsg also uses numpy, but not everything! (ezmsg-zmq for example)
This should be a quick fix. I'll go straight to main.

**Comment by griffinmilsap** [comment]
@cboulay I don't know that numpy is actually a dependency of this package.  I've always treated it as an optional dependency and a testing dependency because our tests rely on it and AxisArray depends on it, but we don't require users to use AxisArray if they don't want.  

I take quite a bit of pride in stating that ezmsg core has no dependencies (typing-extensions doesn't count IMO) and would like to keep it that way :P

**Comment by griffinmilsap** [comment]
Im happy to have the try-except block in there for now.  I predict that we will have a lot of activity in AxisArray for the foreseeable future, but the rest of core is pretty stable at the moment.  Moving AxisArray to sigproc had crossed my mind but I don't like having to bring in the whole sigproc library for a message definition. For now let's keep it in core with the try except block around the numpy import, but we may consider making AxisArray it's own little package if it gets enough features or possibly including it in a ezmsg-std-msgs repo of common message types (which is what ROS does)
